services:
  varnish:
    profiles:
      - frontend
    image: varnish:latest
    ports:
      - 8080:80
    depends_on:
      - jooycar-web
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
  jooycar-web:
    profiles:
      - frontend
    image: jooycar-web
    ports:
      - 3000:3000
    environment:
      - NUXT_PRIVATE_API_URL=http://jooycar-api:4000
      - NUXT_API_URL=http://localhost:4000
    depends_on:
      - jooycar-api
  jooycar-api:
    profiles:
      - build
    build:
      context: .
      dockerfile: Dockerfile
    image: jooycar-api
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      - PORT=4000

      # DB
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASS=developmentpassword
      - DB_NAME=jooycar

      # MAPBOX
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1Ijoic3JncmNwIiwiYSI6ImNsbmM5NjF1NTBrZzMyam56ZjU2cXVqcmMifQ.W1dagNg4HWsXzzyxfslLhQ

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=developmentpassword

volumes:
  mongodb_data:
